name: StackMob_1.12.2
main: uk.antiperson.stackmob.StackMob
version: ${project.version}
api-version: 1.12.2
softdepend: [WorldGuard, MythicMobs, ProtocolLib, ClearLag, MyPet, mcMMO, Jobs, Citizens]
author: antiPerson, Jarrod Wardell
website: https://www.spigotmc.org/resources/stackmob-enhance-your-servers-performance-without-the-sacrifice.29999/
description: A plugin that aims to improve performance by 'stacking' entities together, with attempts to perserve game mechanics. - Modified to run in 1.12.2
commands:
  stackmob:
    aliases: [sm]
    permission: stackmob.admin
    description: The main command of stackmob, which allows for manipulation of stacks.
    permission-message: No permission!